### ISSUE TITLE
Copy button and album title is not vertically aligned

### ISSUE THREAD

**Issue by Row** [Row/metal-archives-userscripts#4]
Should be vertically aligned.

Chrome 77.0, OSX
<img width="745" alt="Mumakil_-_Encyclopaedia_Metallum__The_Metal_Archives" src="https://user-images.githubusercontent.com/359525/67182421-72282180-f3df-11e9-9873-e8ce5706d01a.png">

**Comment by zainahmed24** [comment]
can  do that ?

**Comment by Row** [comment]
> can do that ?

sure!

**Comment by zainahmed24** [comment]
how can i run this file its only js file?

**Comment by Row** [comment]
This is a userscript. A userscript is basically a custom script that extends the functionality of a webpage or webpages.  

To run the code you need:
* Install a userscript handler e.g https://www.tampermonkey.net/ see install instructions here: https://www.youtube.com/watch?v=cu4XeYtqXbM
* Then you open the raw .user.js file. Go to https://github.com/Row/metal-archives-userscripts/blob/master/ma-copy-artist-album-to-clipboard.user.js , then you click the "raw" button at the top of the code. Tampermonkey will handle the installation of the script.
* Then you visit https://www.metal-archives.com/bands/Cannibal_Corpse/186 where this userscript should show an button in front of each album
* To edit the code you click the Tampermonkey icon in your browser, select "Dashboard" then you will find the script there.

Good luck and have fun.

**Comment by Row** [comment]
It seems that this is not an issue anymore, @zainahmed24 if you're still looking into this feel free to look at the other issues instead.
