### ISSUE TITLE
Switching between release types the copy button is not rendered

### ISSUE THREAD

**Issue by Row** [Row/metal-archives-userscripts#6]
Reproduce:

1. Go to Metallica https://www.metal-archives.com/bands/Metallica/125
2. Notice the different release types Complete discography, Main, Lives, Demos, Misc.
3. Change between them and notice that the copy button disappear. 

![Oct-05-2020 10-02-27](https://user-images.githubusercontent.com/359525/95054286-f3142200-06f1-11eb-8e85-2388d5172aad.gif)

**Comment by nagy3n** [comment]
I can't see a copy button without touching anything
![image](https://user-images.githubusercontent.com/11620728/95424953-2f42bf00-094c-11eb-9a40-994fed11e4f4.png)

**Comment by Row** [comment]
@nagy3n thanks!
